import { beforeEach, expect, it, vi } from 'vitest';
import { render, screen, fireEvent, waitFor, act } from '@testing-library/react';
import { HistoricalPreviewPanel } from '../components/HistoricalPreviewPanel';
import { useAuthStore } from '../stores/authStore';
import apiClient from '../api/apiClient';
import { previewHistoricalFixture, type HistoricalPreview } from '../api/exportsApi';
vi.mock('../api/apiClient', () => ({ default: { post: vi.fn() } }));
const response: HistoricalPreview = { businessId: 'b', label: 'Preview only — no data will be saved.', synthetic: true, writesPerformed: false, persistenceAvailable: false, confirmationAvailable: false,
  summary: { totalRows: 1, validRows: 0, warningRows: 1, rejectedRows: 0, ambiguousRows: 0, notFoundRows: 0, outOfScopeRows: 0, duplicateRows: 0 },
  unchangedAreas: ['Current and physical stock', 'Financial totals'], rows: [{ rowIdentifier: 'row-1', case: 'missing-facts', match: 'MATCHED', outcome: 'WARNING', duplicate: false,
    reasons: [], unchangedCurrentValues: { currentStock: '8.125', catalogName: 'Current item' },
    provenance: { sourceIdentifier: 'synthetic-source', sourceKind: 'SyntheticFixture', importIdentifier: 'import-1', rowIdentifier: 'row-1', sourceRowIdentifier: 'source-row-1', actor: 'u', recordedAt: '2026-10-02T00:00:00Z', sourceTimestamp: null, priorRevision: null, correctionReason: null },
    fields: [{ field: 'sellingRate', state: 'UNKNOWN', outcome: 'WARNING', proposedValue: null, reasonCode: 'UNKNOWN', message: 'Remains null.', originalAllowedValue: null, sourceCell: null }, { field: 'openingStock', state: 'KNOWN', outcome: 'VALID', proposedValue: '0', reasonCode: 'SOURCE_VALUE_VALIDATED', message: 'Historical metadata only.', originalAllowedValue: '0', sourceCell: 'cell-1' }] }] };
beforeEach(() => { vi.clearAllMocks(); useAuthStore.setState({ user: { id: 'u', name: 'Owner', email: 'synthetic@test.local', businesses: [], currentBusiness: { businessId: 'b', businessName: 'Synthetic', role: 'Owner', permissions: [] } } }); vi.mocked(apiClient.post).mockResolvedValue({ data: structuredClone(response) }); });
it('starts with synthetic selectors and an honest preview-only empty state', () => { render(<HistoricalPreviewPanel />); expect(screen.getByText('Preview only — no data will be saved.')).toBeVisible(); expect(screen.getAllByRole('option')).toHaveLength(6); expect(apiClient.post).not.toHaveBeenCalled(); expect(screen.queryByRole('button', { name: /confirm|commit|save/i })).toBeNull(); });
it('renders independent states, zero, provenance, proposals and unchanged current values', async () => { render(<HistoricalPreviewPanel />); fireEvent.click(screen.getByRole('button')); await screen.findByText('1 synthetic rows checked. No data saved.'); fireEvent.click(screen.getByText('missing-facts · WARNING · MATCHED')); expect(screen.getByText('UNKNOWN · WARNING')).toBeVisible(); expect(screen.getByText('Proposed: NULL — no value inferred')).toBeVisible(); expect(screen.getByText('Proposed: 0')).toBeVisible(); expect(screen.getByText('synthetic-source')).toBeVisible(); expect(screen.getByText('8.125')).toBeVisible(); expect(apiClient.post).toHaveBeenCalledWith('/exports/historical/preview', { fixtureId: 'mixed' }); });
it('prevents repeated requests and recovers after a failed preview', async () => { let reject!: (error: unknown) => void; vi.mocked(apiClient.post).mockReturnValue(new Promise((_, r) => { reject = r; })); render(<HistoricalPreviewPanel />); fireEvent.click(screen.getByRole('button')); expect(screen.getByRole('button')).toBeDisabled(); fireEvent.click(screen.getByRole('button')); expect(apiClient.post).toHaveBeenCalledTimes(1); reject(new Error('Preview unavailable. Try again.')); await screen.findByRole('alert'); expect(screen.getByRole('button')).toBeEnabled(); });
it('clears old results when selecting another fixture', async () => { render(<HistoricalPreviewPanel />); fireEvent.click(screen.getByRole('button')); await screen.findByText('1 synthetic rows checked. No data saved.'); fireEvent.change(screen.getByRole('combobox'), { target: { value: 'conflicts' } }); expect(screen.queryByText('missing-facts · WARNING · MATCHED')).toBeNull(); fireEvent.click(screen.getByRole('button')); await waitFor(() => expect(apiClient.post).toHaveBeenLastCalledWith('/exports/historical/preview', { fixtureId: 'conflicts' })); });
it.each(['Manager', 'Staff', 'Admin'])('denies %s even with forged permissions', async role => { const user = useAuthStore.getState().user!; useAuthStore.setState({ user: { ...user, currentBusiness: { ...user.currentBusiness!, role, permissions: ['reports.view', 'catalog.edit', 'purchase.edit'] } } }); render(<HistoricalPreviewPanel />); expect(screen.queryByRole('button')).toBeNull(); await expect(previewHistoricalFixture('valid')).rejects.toThrow('access is unavailable'); expect(apiClient.post).not.toHaveBeenCalled(); });
it.each(['writesPerformed', 'persistenceAvailable', 'confirmationAvailable'])('rejects unsafe %s flags', async flag => { vi.mocked(apiClient.post).mockResolvedValue({ data: { ...response, [flag]: true } }); await expect(previewHistoricalFixture('valid')).rejects.toThrow('unsafe'); });
it('rejects a late result after business or membership scope changes', async () => { let resolve!: (value: unknown) => void; vi.mocked(apiClient.post).mockReturnValue(new Promise(r => { resolve = r; })); const pending = previewHistoricalFixture('valid'); const user = useAuthStore.getState().user!; useAuthStore.setState({ user: { ...user, currentBusiness: { ...user.currentBusiness!, businessId: 'foreign' } } }); resolve({ data: response }); await expect(pending).rejects.toThrow('scope changed'); });
it('hides the preview immediately when membership is revoked', async () => { render(<HistoricalPreviewPanel />); fireEvent.click(screen.getByRole('button')); await screen.findByText('1 synthetic rows checked. No data saved.'); const user = useAuthStore.getState().user!; act(() => useAuthStore.setState({ user: { ...user, currentBusiness: { ...user.currentBusiness!, role: 'Manager' } } })); expect(screen.queryByText('Historical data preview')).toBeNull(); });
