import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import apiClient from '../api/apiClient';
import { PageHeader } from '../components/ui';
import { useAuthStore } from '../stores/authStore';
import { hasPermission } from '../auth/Guards';
import { purchaseErrorMessage } from '../lib/purchaseValidation';
type Task = { key: string; description: string; isCompleted: boolean };
type Template = { slot: number; key: string; description: string; priority: number; isActive: boolean };
type Line = { catalogItemId: string; itemName: string; unit: string; quantityUsed: number; closingQty: number; expectedVersion: string; notes?: string };
type Report = { method: string; items: { id: string; name: string; currentStock: number; used7d: number; used30d: number; idleDays: number; movementStatus: string }[] };
const field = 'w-full rounded border border-slate-300 p-3 min-w-0';
export default function OperationsPage() {
 const user = useAuthStore(s => s.user); const cache = useQueryClient(); const [edits, setEdits] = useState<Record<string, string>>({}); const [templates, setTemplates] = useState<Template[] | null>(null);
 const checklist = useQuery({ queryKey: ['operations', 'checklist'], queryFn: async () => (await apiClient.get<{ morning: Task[]; midday: Task[]; evening: Task[]; completionPercentage: number }>('/operations/checklist/today')).data });
 const usage = useQuery({ queryKey: ['operations', 'usage'], queryFn: async () => (await apiClient.get<{ lines: Line[] }>('/operations/usage/today')).data });
 const report = useQuery({ queryKey: ['operations', 'report'], queryFn: async () => (await apiClient.get<Report>('/operations/reports/summary')).data });
 const mutation = useMutation({ mutationFn: async ({ path, body, method = 'post' }: { path: string; body?: unknown; method?: 'post' | 'put' }) => apiClient[method](path, body), onSuccess: () => { setEdits({}); setTemplates(null); for (const key of ['operations', 'stock', 'catalog', 'dashboard', 'reports']) void cache.invalidateQueries({ queryKey: [key] }); } });
 const [localError, setLocalError] = useState('');
 const error = checklist.error || usage.error || report.error || mutation.error;
 const canEditTasks = ['Owner', 'Admin', 'Manager', 'SuperAdmin'].includes(user?.currentBusiness?.role ?? '');
 return <div className="space-y-6"><PageHeader title="Daily Operations" subtitle="Staff checklist, daily usage and stock movement summaries." />
 {(error || localError) && <div role="alert" className="text-red-700">{localError || purchaseErrorMessage(error)} <button onClick={() => { setLocalError(''); void cache.invalidateQueries({ queryKey: ['operations'] }); }}>Retry</button></div>}
 {checklist.isLoading ? <p role="status">Loading checklist…</p> : checklist.data && <section className="bg-white rounded-xl border p-4 space-y-4"><h2 className="text-lg font-semibold">Your daily checklist · {checklist.data.completionPercentage}%</h2><div className="grid md:grid-cols-3 gap-4">{(['morning', 'midday', 'evening'] as const).map((slot, index) => <div key={slot}><h3 className="capitalize font-semibold">{slot}</h3>{checklist.data[slot].map(t => <label key={t.key} className="flex items-center gap-3 min-h-12"><input type="checkbox" checked={t.isCompleted} disabled={t.isCompleted || mutation.isPending} onChange={() => mutation.mutate({ path: `/operations/checklist/${index}/${t.key}`, body: {} })} />{t.description}</label>)}{!checklist.data[slot].length && <p>No tasks for this slot.</p>}</div>)}</div>
 {canEditTasks && <button className="underline min-h-12" onClick={async () => { try { setTemplates((await apiClient.get<Template[]>('/operations/checklist/templates')).data); } catch (e) { setLocalError(purchaseErrorMessage(e)); } }}>Edit checklist templates</button>}
 {templates && <form className="space-y-3" onSubmit={e => { e.preventDefault(); mutation.mutate({ path: '/operations/checklist/templates', method: 'put', body: templates }); }}>{templates.map((t, i) => <div className="grid sm:grid-cols-[8rem_1fr_auto] gap-2" key={i}><select aria-label={`Task ${i + 1} slot`} className={field} value={t.slot} onChange={e => setTemplates(templates.map((r, n) => n === i ? { ...r, slot: Number(e.target.value) } : r))}><option value={0}>Morning</option><option value={1}>Midday</option><option value={2}>Evening</option></select><input aria-label={`Task ${i + 1} description`} className={field} required maxLength={255} value={t.description} onChange={e => setTemplates(templates.map((r, n) => n === i ? { ...r, description: e.target.value } : r))} /><button type="button" onClick={() => setTemplates(templates.filter((_, n) => n !== i))}>Remove task</button></div>)}<button type="button" className="p-3" onClick={() => setTemplates([...templates, { slot: 0, key: `task_${Date.now()}`, description: '', priority: templates.length + 1, isActive: true }])}>Add task</button><button disabled={mutation.isPending || !templates.length} className="p-3 rounded bg-emerald-800 text-white">Save templates</button></form>}
 </section>}
 <section className="bg-white rounded-xl border p-4 space-y-4"><h2 className="text-lg font-semibold">Daily usage</h2><p>Enter the total used today. Saving replaces today's recorded quantity.</p>{usage.isLoading && <p role="status">Loading items…</p>}{usage.data?.lines.length === 0 && <p>No active catalog items.</p>}
 <form onSubmit={e => { e.preventDefault(); const lines = usage.data?.lines.filter(l => edits[l.catalogItemId] !== undefined).map(l => ({ catalogItemId: l.catalogItemId, expectedVersion: l.expectedVersion, quantityUsed: Number(edits[l.catalogItemId]) })); if (lines?.length) mutation.mutate({ path: '/operations/usage', body: { lines } }); }} className="space-y-3">
 {usage.data?.lines.map(l => <div key={l.catalogItemId} className="grid sm:grid-cols-[1fr_10rem] gap-2 border-b pb-3"><div><label htmlFor={l.catalogItemId} className="font-medium">{l.itemName}</label><p className="text-sm text-slate-500">Stock: {l.closingQty} {l.unit}</p></div><input id={l.catalogItemId} className={field} type="number" min={0} step="0.0001" required disabled={!hasPermission(user, 'stock.adjust')} value={edits[l.catalogItemId] ?? l.quantityUsed} onChange={e => setEdits({ ...edits, [l.catalogItemId]: e.target.value })} /></div>)}
 {hasPermission(user, 'stock.adjust') && <button disabled={mutation.isPending || !Object.keys(edits).length} className="px-4 py-3 rounded bg-emerald-800 text-white disabled:opacity-50">Save daily usage</button>}</form></section>
 <section className="bg-white rounded-xl border p-4 space-y-3"><h2 className="text-lg font-semibold">Stock movement summary</h2><p className="text-sm">Rule-based · 7 and 30 day usage, with stock age thresholds from the reference.</p>{report.isLoading && <p role="status">Loading summary…</p>}{report.data?.items.length === 0 && <p>No stock activity yet.</p>}<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className="text-left p-2">Item</th><th>Status</th><th>7 day usage</th><th>30 day usage</th></tr></thead><tbody>{report.data?.items.map(i => <tr key={i.id}><td className="p-2">{i.name}</td><td>{i.movementStatus.replaceAll('_', ' ')}</td><td className="text-center">{i.used7d}</td><td className="text-center">{i.used30d}</td></tr>)}</tbody></table></div>{hasPermission(user, 'stock.adjust') && <button disabled={mutation.isPending} className="underline min-h-12" onClick={() => mutation.mutate({ path: '/operations/snapshot/materialize' })}>Save today's snapshot</button>}</section>
 </div>;
}
