import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import apiClient from '../api/apiClient';
import { PageHeader } from '../components/ui';
import { useAuthStore } from '../stores/authStore';
import { hasPermission } from '../auth/hasPermission';
import { purchaseErrorMessage } from '../lib/purchaseValidation';

type Task = { key: string; description: string; isCompleted: boolean; notes?: string };
type Template = { slot: number; key: string; description: string; priority: number; isActive: boolean };
type Line = { catalogItemId: string; itemName: string; unit: string; openingQty: number; purchasedQty: number; quantityUsed: number; closingQty: number; expectedVersion: string; notes?: string; date?: string };
type Assignment = { id: string; staffId: string; staffName: string; taskType: string; referenceId?: string; status: string; correctionNote?: string; assignedAt: string; completedAt?: string; version: string };
type Report = { method: string; items: { id: string; name: string; used7d: number; used30d: number; movementStatus: string; agingBucket: string; lastMovementAt?: string }[]; supplierFrequency: { supplierId: string; supplierName: string; purchaseCount: number }[] };
const field = 'w-full rounded border border-slate-300 p-3 min-w-0 disabled:bg-slate-50';
const button = 'px-4 py-3 rounded bg-emerald-800 text-white disabled:opacity-50';
const section = 'bg-white rounded-xl border p-4 space-y-4 min-w-0';
const slots = ['morning', 'midday', 'evening'] as const;
const today = () => new Date().toISOString().slice(0, 10);
export default function OperationsPage() {
  const user = useAuthStore(s => s.user); const cache = useQueryClient(); const role = user?.currentBusiness?.role ?? '';
  const canEdit = ['Owner', 'Admin', 'Manager', 'SuperAdmin'].includes(role), canAssign = ['Owner', 'Admin', 'SuperAdmin'].includes(role), canAdjust = hasPermission(user, 'stock.adjust');
  const canStock = hasPermission(user, 'stock.view'), canReport = hasPermission(user, 'reports.view');
  const [edits, setEdits] = useState<Record<string, { quantity: string; notes: string }>>({});
  const [templates, setTemplates] = useState<Template[] | null>(null); const [notes, setNotes] = useState<Record<string, string>>({});
  const [notice, setNotice] = useState(''), [localError, setLocalError] = useState(''), [status, setStatus] = useState('');
  const [assigning, setAssigning] = useState(false), [assignment, setAssignment] = useState({ staffId: '', taskType: 'general', referenceId: '' });
  const [action, setAction] = useState<{ task: Assignment; rejected: boolean } | null>(null), [correction, setCorrection] = useState('');
  const [dates, setDates] = useState({ fromDate: today(), toDate: today(), itemId: '' });
  const checklist = useQuery({ queryKey: ['operations', 'checklist'], queryFn: async () => (await apiClient.get<{ date: string; morning: Task[]; midday: Task[]; evening: Task[]; completionPercentage: number }>('/operations/checklist/today')).data });
  const summary = useQuery({ queryKey: ['operations', 'checklist-summary'], queryFn: async () => (await apiClient.get<{ totalTasks: number; completedTasks: number }>('/operations/checklist/summary')).data });
  const usage = useQuery({ queryKey: ['operations', 'usage'], enabled: canStock, queryFn: async () => (await apiClient.get<{ lines: Line[] }>('/operations/usage/today')).data });
  const usageSummary = useQuery({ queryKey: ['operations', 'usage-summary'], enabled: canStock, queryFn: async () => (await apiClient.get<{ totalItems: number; missingItems: number; totalQuantityUsed: number }>('/operations/usage/summary')).data });
  const report = useQuery({ queryKey: ['operations', 'report'], enabled: canReport, queryFn: async () => (await apiClient.get<Report>('/operations/reports/summary')).data });
  const tasks = useQuery({ queryKey: ['operations', 'tasks', status], queryFn: async () => (await apiClient.get<Assignment[]>('/operations/tasks', { params: { status: status || undefined } })).data });
  const assignees = useQuery({ queryKey: ['operations', 'assignees'], enabled: canAssign && assigning, queryFn: async () => (await apiClient.get<{ id: string; name: string }[]>('/operations/tasks/assignees')).data });
  const performance = useQuery({ queryKey: ['operations', 'performance'], enabled: canAssign, queryFn: async () => (await apiClient.get<{ staffId: string; staffName: string; completed: number; pending: number; rejected: number }[]>('/operations/tasks/performance')).data });
  const snapshots = useQuery({ queryKey: ['operations', 'snapshots', dates], enabled: canStock && !!dates.fromDate && !!dates.toDate && dates.fromDate <= dates.toDate, queryFn: async () => (await apiClient.get<Line[]>('/operations/snapshots', { params: { ...dates, itemId: dates.itemId || undefined } })).data });
  const mutation = useMutation({ mutationFn: async (v: { path: string; body?: unknown; method: 'post' | 'put'; message: string }) => apiClient[v.method](v.path, v.body), onSuccess: (_, v) => {
    setNotice(v.message); setLocalError('');
    if (v.path === '/operations/usage') setEdits({});
    if (v.path === '/operations/checklist/templates') setTemplates(null);
    if (v.path === '/operations/tasks') { setAssigning(false); setAssignment({ staffId: '', taskType: 'general', referenceId: '' }); }
    setAction(null); setCorrection('');
    for (const key of ['operations', 'stock', 'catalog', 'dashboard', 'reports']) void cache.invalidateQueries({ queryKey: [key] });
  } });
  const failure = checklist.error || summary.error || usage.error || usageSummary.error || report.error || tasks.error || assignees.error || performance.error || snapshots.error || mutation.error;
  const save = (path: string, body: unknown, message: string, method: 'post' | 'put' = 'post') => { setNotice(''); mutation.mutate({ path, body, message, method }); };
  const cancel = (discard: () => void) => { if (window.confirm('Discard unsaved changes?')) discard(); };
  return <div className="space-y-6 min-w-0"><PageHeader title="Daily Operations" subtitle="Staff checklist, daily usage and stock movement summaries." />
    {notice && <p role="status" className="text-emerald-800">{notice}</p>}
    {(failure || localError) && <div role="alert" className="text-red-700">{localError || purchaseErrorMessage(failure)} <button className="underline min-h-12 px-3" onClick={() => { mutation.reset(); setLocalError(''); void cache.invalidateQueries({ queryKey: ['operations'] }); }}>Retry</button></div>}
    <section className={section}><h2 className="text-lg font-semibold">Your daily checklist · {checklist.data?.completionPercentage ?? 0}%</h2>
      {checklist.isLoading && <p role="status">Loading checklist…</p>}{checklist.data && <>
        <p>{checklist.data.date?.slice(0, 10)} · Team progress: {summary.data?.completedTasks ?? 0} / {summary.data?.totalTasks ?? 0} tasks</p>
        <div className="grid md:grid-cols-3 gap-4">{slots.map((slot, index) => <div key={slot}><h3 className="capitalize font-semibold">{slot}</h3>{checklist.data[slot].map(t => <div key={t.key} className="mb-3">
          <label className="flex items-center gap-3 min-h-12"><input type="checkbox" checked={t.isCompleted} disabled={t.isCompleted || mutation.isPending} onChange={() => save('/operations/checklist/' + index + '/' + t.key, { notes: notes[slot + t.key] || undefined }, 'Checklist task completed.')} />{t.description}</label>
          {t.isCompleted ? t.notes && <p className="text-sm break-words">{t.notes}</p> : <input aria-label={t.description + ' notes'} className={field} maxLength={1000} placeholder="Optional notes" disabled={mutation.isPending} value={notes[slot + t.key] ?? ''} onChange={e => setNotes({ ...notes, [slot + t.key]: e.target.value })} />}
        </div>)}{!checklist.data[slot].length && <p>No tasks for this slot.</p>}</div>)}</div>
        {canEdit && <button className="underline min-h-12" disabled={mutation.isPending} onClick={async () => { try { setTemplates((await apiClient.get<Template[]>('/operations/checklist/templates')).data); } catch (e) { setLocalError(purchaseErrorMessage(e)); } }}>Edit checklist templates</button>}
      </>}
      {templates && <form onSubmit={e => { e.preventDefault(); save('/operations/checklist/templates', templates.map((t, i) => ({ ...t, priority: i + 1 })), 'Checklist templates saved.', 'put'); }}><fieldset disabled={mutation.isPending} className="space-y-3"><legend className="font-semibold mb-3">Edit team checklist</legend>
        {templates.map((t, i) => <div className="grid sm:grid-cols-[8rem_1fr_auto] gap-2" key={slotKey(t, i)}><select aria-label={'Task ' + (i + 1) + ' slot'} className={field} value={t.slot} onChange={e => setTemplates(templates.map((r, n) => n === i ? { ...r, slot: Number(e.target.value) } : r))}>{slots.map((s, n) => <option key={s} value={n}>{s}</option>)}</select><input aria-label={'Task ' + (i + 1) + ' description'} className={field} required maxLength={255} value={t.description} onChange={e => setTemplates(templates.map((r, n) => n === i ? { ...r, description: e.target.value } : r))} /><button type="button" className="min-h-12" onClick={() => { if (window.confirm('Remove this checklist task?')) setTemplates(templates.filter((_, n) => n !== i)); }}>Remove task</button></div>)}
        <div className="flex flex-wrap gap-3"><button type="button" className="p-3" onClick={() => setTemplates([...templates, { slot: 0, key: 'task_' + crypto.randomUUID().replaceAll('-', '_'), description: '', priority: templates.length + 1, isActive: true }])}>Add task</button><button disabled={!templates.length} className={button}>Save templates</button><button type="button" className="p-3" onClick={() => cancel(() => setTemplates(null))}>Cancel templates</button></div>
      </fieldset></form>}
    </section>
    <section className={section}><h2 className="text-lg font-semibold">Staff tasks</h2><div className="flex flex-wrap gap-3 items-center"><label>Status<select aria-label="Task status" className={field} value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option>{['assigned', 'accepted', 'completed', 'rejected'].map(s => <option key={s}>{s}</option>)}</select></label>{canAssign && <button className={button} disabled={mutation.isPending} onClick={() => setAssigning(true)}>Assign task</button>}</div>
      {tasks.isLoading && <p role="status">Loading tasks…</p>}{tasks.data?.length === 0 && <p>No tasks match this status. {canAssign ? 'Assign work to a business member.' : 'Your assignments will appear here.'}</p>}
      {assigning && <form onSubmit={e => { e.preventDefault(); save('/operations/tasks', assignment, 'Task assigned.'); }}><fieldset disabled={mutation.isPending || assignees.isLoading} className="grid sm:grid-cols-2 gap-3"><legend className="font-semibold mb-3">New assignment</legend>
        <label>Assigned member<select className={field} required value={assignment.staffId} onChange={e => setAssignment({ ...assignment, staffId: e.target.value })}><option value="">Select a member</option>{assignees.data?.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label>
        <label>Task type<input className={field} required maxLength={64} value={assignment.taskType} onChange={e => setAssignment({ ...assignment, taskType: e.target.value })} /></label><label>Reference ID (optional)<input className={field} maxLength={255} value={assignment.referenceId} onChange={e => setAssignment({ ...assignment, referenceId: e.target.value })} /></label>
        <div className="flex flex-wrap gap-3 items-end"><button className={button} disabled={!assignees.data?.length}>Save assignment</button><button type="button" className="p-3" onClick={() => cancel(() => setAssigning(false))}>Cancel assignment</button></div></fieldset>
        {assignees.isLoading && <p role="status">Loading members…</p>}{assignees.data?.length === 0 && <p>No active business members available.</p>}</form>}
      <div className="space-y-3">{tasks.data?.map(t => <article key={t.id} className="border rounded-lg p-3 space-y-2 break-words"><h3 className="font-semibold">{t.taskType} · {t.status}</h3><p>{t.staffName} · Assigned {t.assignedAt.slice(0, 10)}{t.referenceId && ' · Ref ' + t.referenceId}</p>{t.correctionNote && <p>Note: {t.correctionNote}</p>}{t.completedAt && <p>Finished {t.completedAt.slice(0, 10)}</p>}
        {t.staffId === user?.id && ['assigned', 'accepted'].includes(t.status) && <div className="flex flex-wrap gap-3">{t.status === 'assigned' && <button className={button} disabled={mutation.isPending} onClick={() => save('/operations/tasks/' + t.id + '/accept', { expectedVersion: t.version }, 'Task accepted.')}>Accept task</button>}<button className="underline min-h-12" disabled={mutation.isPending} onClick={() => { setAction({ task: t, rejected: false }); setCorrection(''); }}>Complete task</button><button className="underline min-h-12" disabled={mutation.isPending} onClick={() => { setAction({ task: t, rejected: true }); setCorrection(''); }}>Reject task</button></div>}
      </article>)}</div>
      {action && <form className="border rounded p-3" onSubmit={e => { e.preventDefault(); save('/operations/tasks/' + action.task.id + '/complete', { expectedVersion: action.task.version, rejected: action.rejected, correctionNote: correction || undefined }, action.rejected ? 'Task rejected.' : 'Task completed.'); }}><fieldset disabled={mutation.isPending} className="space-y-3"><legend>{action.rejected ? 'Reject' : 'Complete'} {action.task.taskType}</legend><label className="block">Correction note (optional)<textarea className={field} maxLength={1000} value={correction} onChange={e => setCorrection(e.target.value)} /></label><div className="flex flex-wrap gap-3"><button className={button}>Confirm {action.rejected ? 'rejection' : 'completion'}</button><button type="button" className="p-3" onClick={() => cancel(() => setAction(null))}>Cancel action</button></div></fieldset></form>}
      {canAssign && <div><h3 className="font-semibold">Staff performance</h3>{performance.isLoading && <p role="status">Loading performance…</p>}{performance.data?.length === 0 && <p>No assignment history yet.</p>}{performance.data?.map(p => <p key={p.staffId}>{p.staffName}: {p.completed} completed · {p.pending} pending · {p.rejected} rejected</p>)}</div>}
    </section>
    {canStock && <><section className={section}><h2 className="text-lg font-semibold">Daily usage</h2><p>Enter the total used today. Saving replaces today's recorded quantity.</p>{usageSummary.data && <p>{usageSummary.data.totalItems} items logged · {usageSummary.data.missingItems} missing · {usageSummary.data.totalQuantityUsed} total used</p>}{usage.isLoading && <p role="status">Loading items…</p>}{usage.data?.lines.length === 0 && <p>No active catalog items. Add items through the catalog to record usage.</p>}
      <form onSubmit={e => { e.preventDefault(); const lines = usage.data?.lines.filter(l => edits[l.catalogItemId]).map(l => ({ catalogItemId: l.catalogItemId, expectedVersion: l.expectedVersion, quantityUsed: Number(edits[l.catalogItemId].quantity), notes: edits[l.catalogItemId].notes || undefined })); if (lines?.length) save('/operations/usage', { lines }, 'Daily usage saved.'); }}><fieldset disabled={mutation.isPending || !canAdjust} className="space-y-3">
        {usage.data?.lines.map(l => { const value = edits[l.catalogItemId] ?? { quantity: String(l.quantityUsed), notes: l.notes ?? '' }; return <div key={l.catalogItemId} className="grid sm:grid-cols-[1fr_10rem_1fr] gap-3 border-b pb-3"><div><label htmlFor={l.catalogItemId} className="font-medium">{l.itemName}</label><p className="text-sm text-slate-500">Opening {l.openingQty} · Received {l.purchasedQty} · Stock {l.closingQty} {l.unit}</p></div><input aria-label={l.itemName + ' quantity used'} id={l.catalogItemId} className={field} type="number" min={0} max={1000000000} step="0.0001" required value={value.quantity} onChange={e => setEdits({ ...edits, [l.catalogItemId]: { ...value, quantity: e.target.value } })} /><input aria-label={l.itemName + ' usage notes'} className={field} maxLength={1000} placeholder="Optional notes" value={value.notes} onChange={e => setEdits({ ...edits, [l.catalogItemId]: { ...value, notes: e.target.value } })} /></div>; })}
        {canAdjust && <div className="flex flex-wrap gap-3"><button disabled={!Object.keys(edits).length} className={button}>Save daily usage</button><button type="button" className="p-3" disabled={!Object.keys(edits).length} onClick={() => cancel(() => setEdits({}))}>Cancel usage edits</button></div>}
      </fieldset></form>
    </section>
    <section className={section}><h2 className="text-lg font-semibold">Usage snapshot history</h2><div className="grid sm:grid-cols-3 gap-3"><label>From date<input type="date" className={field} value={dates.fromDate} onChange={e => setDates({ ...dates, fromDate: e.target.value })} /></label><label>To date<input type="date" className={field} value={dates.toDate} onChange={e => setDates({ ...dates, toDate: e.target.value })} /></label><label>Snapshot item<select className={field} value={dates.itemId} onChange={e => setDates({ ...dates, itemId: e.target.value })}><option value="">All items</option>{usage.data?.lines.map(l => <option key={l.catalogItemId} value={l.catalogItemId}>{l.itemName}</option>)}</select></label></div>{dates.fromDate > dates.toDate && <p role="alert">From date must be on or before to date.</p>}
      {snapshots.isLoading && <p role="status">Loading snapshots…</p>}{snapshots.data?.length === 0 && <p>No snapshots for this period. Save today's snapshot or log usage to start the history.</p>}
      <div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr>{['Date', 'Item', 'Opening', 'Received', 'Used', 'Closing'].map(h => <th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{snapshots.data?.map(l => <tr key={l.date + l.catalogItemId}><td className="p-2 whitespace-nowrap">{l.date?.slice(0, 10)}</td><td className="p-2">{l.itemName}</td><td className="p-2">{l.openingQty}</td><td className="p-2">{l.purchasedQty}</td><td className="p-2">{l.quantityUsed}</td><td className="p-2">{l.closingQty}</td></tr>)}</tbody></table></div>{canAdjust && <button disabled={mutation.isPending} className={button} onClick={() => save('/operations/snapshot/materialize', undefined, "Today's snapshot saved.")}>Save today's snapshot</button>}
    </section>
    </>}{canReport && <section className={section}><h2 className="text-lg font-semibold">Stock movement summary</h2><p className="text-sm">Rule-based · 7 and 30 day usage, with stock age thresholds from the reference.</p>{report.isLoading && <p role="status">Loading summary…</p>}{report.data?.items.length === 0 && <p>No stock activity yet.</p>}<div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr>{['Item', 'Status', 'Stock age', 'Last movement', '7 day usage', '30 day usage'].map(h => <th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{report.data?.items.map(i => <tr key={i.id}><td className="p-2">{i.name}</td><td className="p-2">{i.movementStatus.replaceAll('_', ' ')}</td><td className="p-2">{i.agingBucket}</td><td className="p-2 whitespace-nowrap">{i.lastMovementAt?.slice(0, 10) ?? 'No movement'}</td><td className="p-2">{i.used7d}</td><td className="p-2">{i.used30d}</td></tr>)}</tbody></table></div><h3 className="font-semibold">Supplier frequency · this month</h3>{report.data?.supplierFrequency.length === 0 && <p>No purchases this month.</p>}{report.data?.supplierFrequency.map(s => <p className="break-words" key={s.supplierId}>{s.supplierName}: {s.purchaseCount} purchases</p>)}</section>}
  </div>;
}
function slotKey(t: Template, index: number) { return t.key + index; }
