import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import apiClient from '../api/apiClient';
import { PageHeader } from '../components/ui';
import { SafeImage } from '../components/SafeImage';
import { useAuthStore } from '../stores/authStore';
import { hasPermission } from '../auth/Guards';
import { purchaseErrorMessage } from '../lib/purchaseValidation';
type Profile = { name: string; brandingTitle?: string; brandingLogoUrl?: string; gstNumber?: string; address?: string; phone?: string; contactEmail?: string; version: string; hasUploadedLogo: boolean; logoUploadAvailable: boolean };
type Preferences = { notificationsEnabled: boolean; notificationKinds: string[] };
const kinds = { low_stock: 'Low stock alerts', delivery: 'Delivery updates', stock_variance: 'Stock variance', staff_alert: 'Staff requests & reorder', opening_stock: 'Opening stock reminders', physical_reminder: 'Physical stock reminders' };
export default function SettingsPage() {
 const user = useAuthStore(s => s.user); const cache = useQueryClient(); const owner = ['Owner', 'SuperAdmin'].includes(user?.currentBusiness?.role ?? '');
 const [draft, setDraft] = useState<Profile | null>(null); const [notice, setNotice] = useState(''); const [uploadError, setUploadError] = useState('');
 const profile = useQuery({ queryKey: ['settings', 'business'], queryFn: async () => (await apiClient.get<Profile>('/settings/business')).data });
 const preferences = useQuery({ queryKey: ['settings', 'notifications'], queryFn: async () => (await apiClient.get<Preferences>('/settings/notifications')).data });
 const update = useMutation({ mutationFn: async (d: Profile) => (await apiClient.put<Profile>('/settings/business', d)).data, onSuccess: d => { cache.setQueryData(['settings', 'business'], d); setDraft(null); setNotice('Business profile saved.'); } });
 const prefs = useMutation({ mutationFn: async (d: Preferences) => (await apiClient.put('/settings/notifications', d)).data, onSuccess: d => { cache.setQueryData(['settings', 'notifications'], d); setNotice('Notification preferences saved.'); } });
 const imageMutation = useMutation({ mutationFn: async (file: File | null) => {
   if (file) { if (file.size > 2 * 1024 * 1024 || !['image/png', 'image/jpeg', 'image/webp'].includes(file.type)) throw new Error('Use JPEG, PNG or WebP up to 2 MB.'); const data = new FormData(); data.append('file', file); data.append('version', profile.data!.version); return (await apiClient.post('/settings/business/logo', data, { headers: { 'Content-Type': 'multipart/form-data' } })).data; }
   return (await apiClient.delete('/settings/business/logo', { params: { version: profile.data!.version } })).data;
 }, onSuccess: d => { cache.setQueryData(['settings', 'business'], d); setNotice('Business logo updated.'); }, onError: e => setUploadError(purchaseErrorMessage(e)) });
 const values = draft ?? profile.data; const failure = profile.error || preferences.error || update.error || prefs.error;
 return <div className="space-y-6"><PageHeader title="Settings" subtitle="Business profile, notifications and workspace shortcuts." />{notice && <p role="status" className="text-emerald-800">{notice}</p>}{failure && <p role="alert" className="text-red-700">{purchaseErrorMessage(failure)} <button onClick={() => void cache.invalidateQueries({ queryKey: ['settings'] })}>Retry</button></p>}
 <section className="rounded-xl border bg-white p-4 space-y-4"><h2 className="text-lg font-semibold">Business profile</h2>{profile.isLoading && <p role="status">Loading profile…</p>}{values && <><SafeImage key={values.version} src={values.hasUploadedLogo ? '/settings/business/logo' : values.brandingLogoUrl} authenticated={values.hasUploadedLogo} alt="Business logo" />
 <form className="grid sm:grid-cols-2 gap-4" onSubmit={e => { e.preventDefault(); update.mutate(values); }}>{(['name', 'brandingTitle', 'gstNumber', 'address', 'phone', 'contactEmail', 'brandingLogoUrl'] as const).map(key => <label className="block min-w-0 text-sm" key={key}>{{ name: 'Business name', brandingTitle: 'Display title', gstNumber: 'GST number', address: 'Address', phone: 'Phone', contactEmail: 'Contact email', brandingLogoUrl: 'Logo URL (HTTPS)' }[key]}<input className="block w-full min-w-0 border rounded p-3 mt-1" disabled={!owner} required={key === 'name'} type={key === 'contactEmail' ? 'email' : key === 'brandingLogoUrl' ? 'url' : 'text'} value={values[key] ?? ''} onChange={e => setDraft({ ...values, [key]: e.target.value || undefined })} /></label>)}{owner && <button disabled={update.isPending} className="px-4 py-3 rounded bg-emerald-800 text-white">Save profile</button>}</form>
 {owner && <div className="space-y-3">{profile.data?.logoUploadAvailable ? <label className="block">Upload logo (JPEG, PNG, WebP · up to 2 MB)<input aria-label="Upload business logo" className="block w-full text-sm mt-2" type="file" accept="image/png,image/jpeg,image/webp" disabled={imageMutation.isPending} onChange={e => { setUploadError(''); if (e.target.files?.[0]) imageMutation.mutate(e.target.files[0]); e.target.value = ''; }} /></label> : <p>Logo upload is unavailable until storage is configured. You can set an HTTPS logo URL.</p>}{(values.hasUploadedLogo || values.brandingLogoUrl) && <button className="underline min-h-12" disabled={imageMutation.isPending} onClick={() => imageMutation.mutate(null)}>Remove logo</button>}{uploadError && <p role="alert" className="text-red-700">{uploadError}</p>}</div>}</>}
 </section><section className="rounded-xl border bg-white p-4 space-y-3"><h2 className="text-lg font-semibold">Notifications</h2>{preferences.isLoading && <p role="status">Loading preferences…</p>}{preferences.data && <><label className="flex gap-3 items-center min-h-12"><input type="checkbox" checked={preferences.data.notificationsEnabled} disabled={prefs.isPending} onChange={e => prefs.mutate({ ...preferences.data!, notificationsEnabled: e.target.checked })} />Enable notifications</label>{Object.entries(kinds).map(([key, label]) => <label key={key} className="flex gap-3 items-center min-h-12"><input type="checkbox" disabled={prefs.isPending || !preferences.data!.notificationsEnabled} checked={preferences.data!.notificationKinds.includes(key)} onChange={e => prefs.mutate({ ...preferences.data!, notificationKinds: e.target.checked ? [...preferences.data!.notificationKinds, key] : preferences.data!.notificationKinds.filter(k => k !== key) })} />{label}</label>)}</>}</section>
 <section className="rounded-xl border bg-white p-4 space-y-3"><h2 className="text-lg font-semibold">Workspace</h2><div className="flex flex-wrap gap-4">{hasPermission(user, 'purchase.create') && <Link to="/purchases/new" className="underline min-h-12">New purchase</Link>}{hasPermission(user, 'users.view') && <Link to="/users" className="underline min-h-12">Users</Link>}<Link to="/operations" className="underline min-h-12">Daily operations</Link>{hasPermission(user, 'reports.view') && <Link to="/reports" className="underline min-h-12">Reports & exports</Link>}</div></section>
 </div>;
}
